# =============================================
# springboot configurations
# ---------------------------------------------
spring:
  application:
    name: fuse-auth-integration-api
  datasource:
    initialize: false

api:
  title: fuse-auth-integration-api
  description: secured fuse application with keycloak adapter
  version: 1
  hostname: api-auth-integration.apps.arekkusu.io

logging:
  config: classpath:logback.xml

# options from org.apache.camel.spring.boot.CamelConfigurationProperties can be configured here
camel:
  springboot:
    name: fuse-auth-integration-api
    main-run-controller: true
  component:
    servlet:
      mapping:
        contextPath: /api/v${api.version}/*
    jmxEnabled: true

# lets listen on all ports to ensure we can be invoked from the pod ip address
server:
  address: 0.0.0.0
  port: 8080

# lets use a different management port in case you need to listen to HTTP requests on 8080
management:
  security:
    enabled: false
  address: 0.0.0.0
  port: 8081
  metrics:
    export:
      prometheus:
        enabled: true

# =============================================
# springboot actuator configurations
# ---------------------------------------------
# disable all management endpoints except health
endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
  prometheus:
    enabled: true
    # if you want to change the default prometheus endpoint, just change the 'id' to another value.
    id: prometheus

# =============================================
# opentracing configurations
# ---------------------------------------------
opentracing:
  jaeger:
    enabled: true
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      url: http://jaeger-collector:14268/api/traces

jaeger.tracer:
  host: jaeger-agent.microservices.svc
  port: 6831

keycloak:
  ssl-required: external
  realm: test
  resource: fis-api-sample
  auth-server-url: https://test.com/auth
  credentials:
    secret: 123
  use-resource-role-mappings: true
  security-constraints:
    - authRoles:
        - ADMIN
        - T_INT_ADMIN
      securityCollections:
        - name: CREATE
          patterns: /api/v1/agencia
          methods: POST
        - name: DELETE
          patterns: /api/v1/agencia/*
          methods: DELETE
        - name: PUT
          patterns: /api/v1/agencia
          methods: PUT
    - authRoles:
        - BASIC
        - T_INT_BASICO
      securityCollections:
        - name: LIST
          patterns: /api/v1/agencia
          methods: GET
        - name: RETRIEVE
          patterns: /api/v1/agencia/*
          methods: GET

# =============================================
# product api parameters
# ---------------------------------------------
product:
  api-key-name: product
  auth:
    realm: microservices-security
    client-id: product
    grant-type: password
    username: user1
    password: user1
    secret: xxxxx
    auth-server-uri: https://localhost:8080/auth/
  host: localhost
  port: 8080
  context-path: /v1/product

# =============================================
# stock api parameters
# ---------------------------------------------
stock:
  api-key-name: stock
  host: localhost
  port: 8080
  context-path: /v1/stock

# =============================================
# supplier api parameters
# ---------------------------------------------
supplier:
  api-key-name: supplier
  host: localhost
  port: 8080
  context-path: /v1/supplier
